name: Aria2下载直链转存Aliyun
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      Url:
        description: '下载URL'
        required: true
        default: 'https://网址##名称'
      Folder:
        description: '保存目录'
        required: true
        default: 'encrypt_folder'

jobs:
  Aria2-Aliyun:
    runs-on: ubuntu-latest
    services:
      aliyun:
        image: messense/aliyundrive-webdav
        env:
          REFRESH_TOKEN: '${{ secrets.ALIYUN_REFRESH_TOKEN }}'
          PORT: 8080
    steps:
      - uses: actions/checkout@v2
      - name: Aria2 Install
        run: sudo apt install -y aria2 
        
      - name: Downloading
        id: downloading
        run: |
          url="${{ github.event.inputs.Url}}"
          filename=${url##*##}
          downloadurl=${url%##*}
          echo "::set-output name=filename::$filename"
          echo "::set-output name=path::downloads/$filename"
          aria2c --conf $GITHUB_WORKSPACE/aria2.conf --seed-time=0 -d downloads -c $downloadurl -o $filename
          
      - name: upload
        uses: thinkdolabs/curl@v1
        if: steps.downloading.outputs.path != '' && !cancelled() && !failure()
        with:
          args: --upload-file ${{ steps.downloading.outputs.path }}  http://aliyun:8080/${{ steps.downloading.outputs.filename }}
        
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v1.2.3
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
